#!/usr/bin/python3
def raise_exception():
    print(float(['5']))
